export default [
  {
    id: 1,
    sponsor: 1,
    name: 'Эксперт Авито',
    group_specializations_id: null,
  },
  {
    id: 2,
    sponsor: 1,
    name: 'Сообщество Онтико',
    group_specializations_id: null,
  },
  {
    id: 3,
    sponsor: 1,
    name: 'Наставник Яндекс.Практикума',
    group_specializations_id: null,
  },
  {
    id: 4,
    sponsor: 0,
    name: 'Backend',
    group_specializations_id: 'Development',
  },
  {
    id: 5,
    sponsor: 0,
    name: 'Frontend',
    group_specializations_id: 'Development',
  },
  {
    id: 6,
    sponsor: 0,
    name: 'iOS',
    group_specializations_id: 'Development',
  },
  {
    id: 7,
    sponsor: 0,
    name: 'Android',
    group_specializations_id: 'Development',
  },
  {
    id: 8,
    sponsor: 0,
    name: 'System Design',
    group_specializations_id: 'Development',
  },
  {
    id: 9,
    sponsor: 0,
    name: 'Code Review',
    group_specializations_id: 'Development',
  },
  {
    id: 10,
    sponsor: 0,
    name: 'Agile',
    group_specializations_id: 'Management',
  },
  {
    id: 11,
    sponsor: 0,
    name: 'Team Lead/Management',
    group_specializations_id: 'Management',
  },
  {
    id: 12,
    sponsor: 0,
    name: 'Project Management',
    group_specializations_id: 'Management',
  },
  {
    id: 13,
    sponsor: 0,
    name: 'Product Management',
    group_specializations_id: 'Management',
  },
  {
    id: 14,
    sponsor: 0,
    name: 'DevOps/SRE',
    group_specializations_id: 'DevOps',
  },
  {
    id: 15,
    sponsor: 0,
    name: 'Databases',
    group_specializations_id: 'DevOps',
  },
  {
    id: 16,
    sponsor: 0,
    name: 'Сети',
    group_specializations_id: 'DevOps',
  },
  {
    id: 17,
    sponsor: 0,
    name: 'Cloud',
    group_specializations_id: 'DevOps',
  },
  {
    id: 18,
    sponsor: 0,
    name: 'HR',
    group_specializations_id: 'HR',
  },
  {
    id: 19,
    sponsor: 0,
    name: 'Карьера',
    group_specializations_id: 'HR',
  },
  {
    id: 20,
    sponsor: 0,
    name: 'Собеседования',
    group_specializations_id: 'HR',
  },
  {
    id: 21,
    sponsor: 0,
    name: 'Entrepreneurship',
    group_specializations_id: 'HR',
  },
  {
    id: 22,
    sponsor: 0,
    name: 'DevRel',
    group_specializations_id: 'HR',
  },
  {
    id: 23,
    sponsor: 0,
    name: 'Marketing',
    group_specializations_id: 'Marketing',
  },
  {
    id: 24,
    sponsor: 0,
    name: 'Content/Copy',
    group_specializations_id: 'Marketing',
  },
  {
    id: 25,
    sponsor: 0,
    name: 'Data Science/ML',
    group_specializations_id: null,
  },
  {
    id: 26,
    sponsor: 0,
    name: 'UX/UI/Design',
    group_specializations_id: null,
  },
  {
    id: 27,
    sponsor: 0,
    name: 'QA',
    group_specializations_id: null,
  },
  {
    id: 28,
    sponsor: 0,
    name: 'Аналитика',
    group_specializations_id: null,
  },
  {
    id: 29,
    sponsor: 0,
    name: 'Другое',
    group_specializations_id: null,
  },
]
